POST http://localhost:5000/api/auth/register
content-type: application/json
{
    "name": "Test User",
    "email": "miracleolaniyan5@yahoo.com",
    "Role":"ADMIN",
    "password": "password123"
    }